version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    volumes:
      - ./data.yml:/usr/src/app/database.yml
    environment:
      - NODE_ENV=production
    env_file:
      - .env